# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Run daily at 0:01 UTC  
  #schedule:
  #- cron: '1 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 10

      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        python-version: [3.7, 3.8] # 3.6 fails

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python default regression
        working-directory: ./Regression/ReactionRates
        run: |
          python run_regression.py -p DR -a DT  
#              ./run_regression.sh -p DR -a DT

      - name: Upload artifacts    
        uses: actions/upload-artifact@v2
        with:
          name: regression-artifacts
          path: ./Regression/ReactionRates
          retention-days: 1

      - name: Download artifacts    
        uses: actions/download-artifact@v2
        with:
          path: ./Regression/ReactionRates
          name: regression-artifacts
          retention-days: 1

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./Regression/ReactionRates
